s3:
  host: public-audio.s3.i.sz.shopee.io
  accessKey: YH0CM2SQIA03Z2XUK8R5
  secretKey: QXEeEGOLOEhAQqcxoms2EjsRZ3wOgVELjMeBuVCf
  bucket: audiencemanager

kafka:
  brokers:
    - kafka-public-live-00.sg2.i.sz.shopee.io:30002
    - kafka-public-live-01.sg2.i.sz.shopee.io:30002
    - kafka-public-live-02.sg2.i.sz.shopee.io:30002
    - kafka-public-live-03.sg2.i.sz.shopee.io:30002
    - kafka-public-live-04.sg2.i.sz.shopee.io:30002
    - kafka-public-live-05.sg2.i.sz.shopee.io:30002
  topic: audience_manager_data_live_sg
  metaTopic: audience_manager_task_meta_live

crm:
  credential:
    key: crm_am_appkey
    secret: a44b9a6e3f8f42dc9d77f53ecffc41a7
  callback:
    id: https://mkt-admin.shopee.co.id
    th: https://mkt-admin.shopee.co.th
    my: https://mkt-admin.shopee.com.my
    br: https://mkt-admin.shopee.com.br
    vn: https://mkt-admin.shopee.vn
    sg: https://mkt-admin.shopee.sg
    tw: https://mkt-admin.shopee.tw
    ph: https://mkt-admin.shopee.ph
    mx: https://mkt-admin.shopee.com.mx
    co: https://mkt-admin.shopee.com.co
    cl: https://mkt-admin.shopee.cl
    pl: https://mkt-admin.shopee.pl
    es: https://mkt-admin.shopee.es
    fr: https://mkt-admin.shopee.fr
    in: https://mkt-admin.shopee.in
    xx: https://mkt-admin.shopee.systems

am:
  callback:
    sg: https://audience.shopee.io/am/adminapi
  credential:
    key: am_appkey
    secret: dfd1c9b0e643675c1b247b38ddb6cfb0
  schema:
    crm: sztoc_audiencemanager
    om: opa_audiencemanager_om
    ads_ops: opa_audiencemanager_ads
    referral: opa_audiencemanager_ads
    crm_attr: opa_audiencemanager_crm_attr
  hdfs:
    crm: /projects/sztoc_audiencemanager/hdfs/prod/am
    om: /projects/opa_audiencemanager_om/hdfs/prod/am
    ads_ops: /projects/opa_audiencemanager_ads/hdfs/prod/am
    referral: /projects/opa_audiencemanager_ads/hdfs/prod/am
    crm_attr: /projects/opa_audiencemanager_crm_attr/hdfs/prod

airflow:
  seatalk: https://openapi.seatalk.io/webhook/group/WZ1OiychQyWrczdEwt6m3Q

redis:
  network: tcp
  addr: localhost:6379
  maxActive: 20
  maxIdle: 20
  idleTimeoutSecond: 240

spark:
  jars:
    - hdfs://R2/projects/sztoc_audiencemanager/jars/aws-java-sdk-bundle-1.11.375.jar
    - hdfs://R2/projects/sztoc_audiencemanager/jars/hadoop-aws-3.2.0-sdi-001.jar
  file: hdfs://R2/projects/sztoc_audiencemanager/executable/test/%s/run_app.py
  apps: |-
    {
      "FilterAudienceUsers": "am_audience_filter",
      "SyncDistributionCrm": "am_distribution_crm",
      "DistributeIncrCalc": "am_distribution_incremental",
      "SyncDistributionCommon": "am_distribution_referral",
      "MergeFiles": "am_merge_files",
      "UpdateAttribute": "am_attribute_update",
      "SyncAudienceRecordHive": "am_sync_analytical_ma"
    }
  pyFiles:
    - hdfs://R2/projects/sztoc_audiencemanager/executable/live/sg/amengine-0.1-py3.9.egg
  archives:
    - hdfs://R2/projects/sztoc_audiencemanager/python/env/am_py_39.tar.gz#env
  sparkConf: |-
    {
      "spark.sql.files.mergeSmallFile.enabled": "true",
      "spark.sql.files.mergeSmallFile.maxBytes": "1073742000",
      "spark.pyspark.python": "./env/bin/python",
      "spark.yarn.appMasterEnv.PYSPARK_PYTHON": "./env/bin/python",
      "spark.yarn.appMasterEnv.PYSPARK_DRIVER_PYTHON": "./env/bin/python",
      "spark.executorEnv.PYSPARK_PYTHON": "./env/bin/python",
      "spark.executorEnv.PYSPARK_DRIVER_PYTHON": "./env/bin/python",
      "spark.dynamicAllocation.enabled": "false"
    }
  livy:
    retry: 3
    rest:
      protocol: http
      url: livy-rest.data-infra.shopee.io
      single:
        create: /batches
        get: /batches/{batchId}
        delete: /batches/{batchId}
        logs: /batches/{batchId}/amlogs/{type}?from={start}&size={logSize}
      interactive:
        create: /sessions
        get: /sessions/{interactiveId}
        delete: /sessions/{interactiveId}
        logs: /sessions/{interactiveId}/amlogs/{type}?from={start}&size={logSize}
        execute: /sessions/{interactiveId}/statements
        query: /sessions/{interactiveId}/statements/{statementId}
    thrift:
      host: jdbc:hive2://livy-thrift.data-infra.shopee.io
      port: 10090
  executor:
    FilterAudienceUsers:
      name: FilterAudienceUsers
      type: single
      business:
        validate:
          - ads_ops # Probably referral
          - crm
          - om
        account:
          ads_ops:
            name: opa_audiencemanager_ads
            password: Cpo5cIq7yfCF
          crm:
            name: sztoc_audiencemanager
            password: ufrSvqgAx80d
          om:
            name: opa_audiencemanager_om
            password: jtTJUwvK3kyg
        concurrency:
          ads_ops: 21
          crm: 40
          om: 24
        queue:
          ads_ops: szopam-prod-ads
          crm: szopam-prod
          om: szopam-prod-om
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 8g
        executorCores: 1
        numExecutors: 68
    SyncDistributionCrm:
      name: SyncDistributionCrm
      type: single
      business:
        validate:
          - crm
        account:
          crm:
            name: haiping.lai
            password: bMHhMu4uQs1X
        concurrency:
          crm: 30
        queue:
          crm: szopam-prod
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 8g
        executorCores: 1
        numExecutors: 10
    DistributeIncrCalc:
      name: DistributeIncrCalc
      type: single
      business:
        validate:
          - ads_ops
          - crm
          - om
        account:
          ads_ops:
            name: opa_audiencemanager_ads
            password: Cpo5cIq7yfCF
          crm:
            name: sztoc_audiencemanager
            password: ufrSvqgAx80d
          om:
            name: opa_audiencemanager_om
            password: jtTJUwvK3kyg
        concurrency:
          ads_ops: 20
          crm: 2
          om: 20
        queue:
          ads_ops: szopam-prod-ads
          crm: szopam-prod
          om: szopam-prod-om
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 8g
        executorCores: 1
        numExecutors: 50
    SyncDistributionCommon:
      name: SyncDistributionCommon
      type: single
      business:
        validate:
          - ads_ops
        account:
          ads_ops:
            name: opa_audiencemanager_ads
            password: Cpo5cIq7yfCF
        concurrency:
          ads_ops: 1
        queue:
          ads_ops: szopam-prod-ads
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 8g
        executorCores: 1
        numExecutors: 20
    MergeFiles:
      name: MergeFiles
      type: single
      business:
        validate:
          - ads_ops
          - crm
          - om
        account:
          ads_ops:
            name: opa_audiencemanager_ads
            password: Cpo5cIq7yfCF
          crm:
            name: sztoc_audiencemanager
            password: ufrSvqgAx80d
          om:
            name: opa_audiencemanager_om
            password: jtTJUwvK3kyg
        concurrency:
          ads_ops: 40
          crm: 40
          om: 40
        queue:
          ads_ops: szopam-prod-ads
          crm: szopam-prod
          om: szopam-prod-om
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 1g
        executorCores: 2
        numExecutors: 1
    UpdateAttribute:
      name: UpdateAttribute
      type: single
      business:
        validate:
          - crm
        account:
          crm:
            name: opa_audiencemanager_crm_attr
            password: qJ5NXNAuu8J4
        concurrency:
          crm: 14
        queue:
          crm: szopam-prod-crm-attr
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 6g
        executorCores: 1
        numExecutors: 20
    SyncAudienceRecordHive:
      name: SyncAudienceRecordHive
      type: single
      business:
        validate:
          - crm
        account:
          crm:
            name: sztoc_audiencemanager
            password: ufrSvqgAx80d
        concurrency:
          crm: 1
        queue:
          crm: szopam-prod
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 8g
        executorCores: 1
        numExecutors: 50


