s3:
  host: s3.i.test.sz.shopee.io
  accessKey: RDB70A2ZWNEEKJ9IY7TK
  secretKey: 2JQg5b9KNsOmBZrHHcqZjzCqFTyOZFmqVf1RzgkB
  bucket: audiencemanager

kafka:
  brokers:
    - kafka-public-test-01.sg2.i.sz.shopee.io:9092
    - kafka-public-test-02.sg2.i.sz.shopee.io:9092
    - kafka-public-test-03.sg2.i.sz.shopee.io:9092
  topic: audience_manager_data_test_sg
  metaTopic: audience_manager_task_meta_test

crm:
  credential:
    key: crm_am_appkey
    secret: ffd0734779dd4215973492e8815b4422
  callback:
    id: https://mkt-admin.test.shopee.co.id
    th: https://mkt-admin.test.shopee.co.th
    my: https://mkt-admin.test.shopee.com.my
    br: https://mkt-admin.test.shopee.com.br
    vn: https://mkt-admin.test.shopee.vn
    sg: https://mkt-admin.test.shopee.sg
    tw: https://mkt-admin.test.shopee.tw
    ph: https://mkt-admin.test.shopee.ph
    mx: https://mkt-admin.test.shopee.com.mx
    co: https://mkt-admin.test.shopee.com.co
    cl: https://mkt-admin.test.shopee.cl
    pl: https://mkt-admin.test.shopee.pl
    es: https://mkt-admin.test.shopee.es
    fr: https://mkt-admin.test.shopee.fr
    in: https://mkt-admin.test.shopee.in
    xx: https://mkt-admin.test.shopee.systems

am:
  callback:
    sg: https://audience.test.shopee.io/am/adminapi
    th: https://audience.test.shopee.co.th/am/adminapi
    tw: https://audience.test.shopee.tw/am/adminapi
    my: https://audience.test.shopee.com.my/am/adminapi
    id: https://audience.test.shopee.co.id/am/adminapi
    vn: https://audience.test.shopee.vn/am/adminapi
    ph: https://audience.test.shopee.ph/am/adminapi
  credential:
    key: am_appkey
    secret: 9709819e6ae87536afab3d8f1ebf76b5
  schema:
    crm: dev_sztoc_audiencemanager
    om: dev_opa_audiencemanager_om
    ads_ops: dev_opa_audiencemanager_ads
    referral: dev_opa_audiencemanager_ads
    crm_attr: dev_opa_audiencemanager_crm_attr
  hdfs:
    crm: /projects/sztoc_audiencemanager/hdfs/dev/am
    om: /projects/opa_audiencemanager_om/hdfs/dev/am
    ads_ops: /projects/opa_audiencemanager_ads/hdfs/dev/am
    referral: /projects/opa_audiencemanager_ads/hdfs/dev/am
    crm_attr: /projects/opa_audiencemanager_crm_attr/hdfs/dev

airflow:
  seatalk: https://openapi.seatalk.io/webhook/group/n8tu6rsWQrmQ0VA_XsOXag

redis:
  network: tcp
  addr: localhost:6379
  maxActive: 20
  maxIdle: 20
  idleTimeoutSecond: 240

spark:
  jars:
    - hdfs://R2/projects/sztoc_audiencemanager/jars/aws-java-sdk-bundle-1.11.375.jar
    - hdfs://R2/projects/sztoc_audiencemanager/jars/hadoop-aws-3.2.0-sdi-001.jar
  file: hdfs://R2/projects/sztoc_audiencemanager/executable/test/%s/run_app.py
  apps: |-
    {
      "FilterAudienceUsers": "am_audience_filter",
      "SyncDistributionCrm": "am_distribution_crm",
      "DistributeIncrCalc": "am_distribution_incremental",
      "SyncDistributionCommon": "am_distribution_referral",
      "MergeFiles": "am_merge_files",
      "UpdateAttribute": "am_attribute_update",
      "SyncAudienceRecordHive": "am_sync_analytical_ma"
    }
  pyFiles:
    - hdfs://R2/projects/sztoc_audiencemanager/executable/test/%s/amengine-0.1-py3.9.egg
  archives:
    - hdfs://R2/projects/sztoc_audiencemanager/python/env/am_py_39.tar.gz#env
  sparkConf: |-
    {
      "spark.sql.files.mergeSmallFile.enabled": "true",
      "spark.sql.files.mergeSmallFile.maxBytes": "1073742000",
      "spark.pyspark.python": "./env/bin/python",
      "spark.yarn.appMasterEnv.PYSPARK_PYTHON": "./env/bin/python",
      "spark.yarn.appMasterEnv.PYSPARK_DRIVER_PYTHON": "./env/bin/python",
      "spark.executorEnv.PYSPARK_PYTHON": "./env/bin/python",
      "spark.executorEnv.PYSPARK_DRIVER_PYTHON": "./env/bin/python",
      "spark.dynamicAllocation.enabled": "false"
    }
  livy:
    retry: 3
    rest:
      protocol: http
      url: livy-rest.data-infra.shopee.io
      single:
        create: /batches
        get: /batches/{batchId}
        state: /batches/{batchId}/state
        delete: /batches/{batchId}
        logs: /batches/{batchId}/amlogs/{type}?from={start}&size={logSize}
      interactive:
        create: /sessions
        get: /sessions/{interactiveId}
        delete: /sessions/{interactiveId}
        logs: /sessions/{interactiveId}/amlogs/{type}?from={start}&size={logSize}
        execute: /sessions/{interactiveId}/statements
        query: /sessions/{interactiveId}/statements/{statementId}
    thrift:
      host: jdbc:hive2://10.173.1.3
      port: 10090
  executor:
    FilterAudienceUsers:
      name: FilterAudienceUsers
      session:
        isBatch: false
        renewIntervalSeconds: 0
      business:
        validate:
          - ads_ops
          - crm
          - om
        account:
          ads_ops:
            name: staging_opa_audiencemanager_ads
            password: Fg5XY4WE5hoF
          crm:
            name: staging_sztoc_audiencemanager
            password: SdKWIYBvo6tT
          om:
            name: staging_opa_audiencemanager_om
            password: NrQnLsK89RjO
        concurrency:
          ads_ops: 3
          crm: 3
          om: 3
        queue:
          ads_ops: szopam-test
          crm: szopam-test
          om: szopam-test
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 6g
        executorCores: 1
        numExecutors: 20
    SyncDistributionCrm:
      name: SyncDistributionCrm
      session:
        isBatch: false
        renewIntervalSeconds: 0
      business:
        validate:
          - crm
        account:
          crm:
            name: haiping.lai
            password: bMHhMu4uQs1X
        concurrency:
          crm: 3
        queue:
          crm: szopam-test
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 5g
        executorCores: 1
        numExecutors: 20
    DistributeIncrCalc:
      name: DistributeIncrCalc
      session:
        isBatch: false
        renewIntervalSeconds: 0
      business:
        validate:
          - ads_ops
          - crm
          - om
        account:
          ads_ops:
            name: staging_opa_audiencemanager_ads
            password: Fg5XY4WE5hoF
          crm:
            name: staging_sztoc_audiencemanager
            password: SdKWIYBvo6tT
          om:
            name: staging_opa_audiencemanager_om
            password: NrQnLsK89RjO
        concurrency:
          ads_ops: 1
          crm: 1
          om: 1
        queue:
          ads_ops: szopam-test
          crm: szopam-test
          om: szopam-test
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 8g
        executorCores: 1
        numExecutors: 20
    SyncDistributionCommon:
      name: SyncDistributionCommon
      session:
        isBatch: false
        renewIntervalSeconds: 0
      business:
        validate:
          - ads_ops
        account:
          ads_ops:
            name: staging_opa_audiencemanager_ads
            password: Fg5XY4WE5hoF
        concurrency:
          ads_ops: 1
        queue:
          ads_ops: szopam-test
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 8g
        executorCores: 1
        numExecutors: 20
    MergeFiles:
      name: MergeFiles
      session:
        isBatch: false
        renewIntervalSeconds: 0
      business:
        validate:
          - ads_ops
          - crm
          - om
        account:
          ads_ops:
            name: staging_opa_audiencemanager_ads
            password: Fg5XY4WE5hoF
          crm:
            name: staging_sztoc_audiencemanager
            password: SdKWIYBvo6tT
          om:
            name: staging_opa_audiencemanager_om
            password: NrQnLsK89RjO
        concurrency:
          ads_ops: 3
          crm: 3
          om: 3
        queue:
          ads_ops: szopam-test
          crm: szopam-test
          om: szopam-test
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 1g
        executorCores: 1
        numExecutors: 2
    UpdateAttribute:
      name: UpdateAttribute
      session:
        isBatch: false
        renewIntervalSeconds: 0 # session will be closed after 1 hour idle
      business:
        validate:
          - crm
        account:
          crm:
            name: staging_opa_audiencemanager_crm_attr
            password: x4mvSV6RMa4A
        concurrency:
          crm: 2
        queue:
          crm: szopam-test
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 6g
        executorCores: 1
        numExecutors: 20
    SyncAudienceRecordHive:
      name: SyncAudienceRecordHive
      session:
        isBatch: false
        renewIntervalSeconds: 0
      business:
        validate:
          - crm
        account:
          crm:
            name: staging_sztoc_audiencemanager
            password: SdKWIYBvo6tT
        concurrency:
          crm: 2
        queue:
          crm: szopam-test
      resource:
        driverMemory: 6g
        driverCores: 1
        executorMemory: 8g
        executorCores: 1
        numExecutors: 20